### ISSUE TITLE
@reflectToAttribute

### ISSUE THREAD

**Issue by adaliszk** [Draccoz/easy-polymer#1]
I miss the reflect to attribute decorator :)

**Comment by Buslowicz** [comment]
Sorry I forgot to add that to readme, it's the `@attr` decorator.
Also please be advised that this is not a production ready library (just added disclaimer at the beginning of the readme). It was an experiment, an attempt to make a repo showing how to build and use decorators with Polymer. Feel free to fork it, tinker with it, or even use it in production, but at your own risk ;). I also mentioned other alternatives for both Polymer V1 and Polymer V2 in the disclaimer I added.
